### ISSUE TITLE
Server error creating new listing with "Other" as the vehicle Make

### ISSUE THREAD

**Issue by pruprecht** [up-shift/motodex-issues#1]
After hitting the "continue" button on the "vehicle details" page when creating a new listing, the following error message appears "Something went wrong (500) We're experiencing some trouble on our end. Please try again soon."

This consistently happens if I choose "Other" as the vehicle make.  If I go back to the vehicle details page using the browser "back" button and change to a different make, then the listing process continues as normal.

This happens on Win10 with both Edge and Firefox, with different motodex users.  Clearing cache/cookies/files doesn't have any effect.

**Comment by up-shift** [comment]
Fixed bug on branch demo-8
